import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "./components/shared";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  applicationName: "Videos website",
  description: "Generated by create next app",
  keywords: ["videos website", "trending videos"],
  metadataBase: new URL("https://videos-website.com"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    images: "/og-image.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} md:px-[5vw]`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
